#!/bin/sh
#/etc/init.d/pseriescollector

APPDIR=/opt/pseriescollector
PID=/var/run/pseriescollector.pid

case "$1" in
   start)
     echo "Starting pseriescollector"
	   export PWD=$APPDIR
     start-stop-daemon --start --quiet --make-pidfile --pidfile $PID --chdir $APPDIR --background --exec ./pseriescollector -- -config $APPDIR/conf/pseriescollector.toml -logs $APPDIR/log
     ;;
   stop)
     echo "Stopping pseriescollector"
     start-stop-daemon --stop --pidfile $PID
	 rm -f $PID
     ;;
   *)
     echo "Usage: /etc/init.d/pseriescollector{start|stop}"
     exit 1
     ;;
esac

exit 0
