
############################
# General Config
############################

[general]
 # InstanceID will be a string identifying the reristor instance , It will be useful when
 # more than one running on the same server, this ID will be shown in the WebUI.
 instanceID = "pseriescollector_PRO"
 # datadir set the directory where the data will be placed , also sqlite db if set as db engine
 # if not set the default datadir will be placed in the configuration directory
 # datadir = "/var/lib/pseriescollector"

 # there are as many logs as devices configured
 # logdir set the Directory path for each device individual log, default is /var/log/pseriescollector
 # logdir = "/var/log/somelogpath"
 # NOTE: main process log is now sent to standard output
 # logLevel set the main process log level
 # valid values: panic,fatal,error,warn,info,debug
 logLevel = "warn"

 ############################
 # DataBase Config
 ############################

[database]
#type sets the sql backend
#valid values sqlite3,mysql
 type = "sqlite3"
# these parameters are only for mysql (use mysql_setup.sql before)
# host = 127.0.0.1:3306
# user = "pseriescollectoruser"
# password = "pseriescollectorpass"
# name sets the database name
 name = "pseriescollector"
#sqllogfile sets the name for a file in the log/ directory where sql backend will write all SQL transactions
#sqllogfile = "sql.log"
 # debug adds extra verbosity to the SQL log
 debug = false



############################
# Self Monitorig Config
############################
#config for sending self monitoring metrics to our default influx db
# Sent Measurements will be <prefix>selfmon_gvm with the following fields
# runtime_goroutines
# *mem.alloc
# *mem.mallocs
# *mem.frees
# *gc.total_pause_ns
# *memory.heap
# *gc.pause_per_second
# *gc.pause_per_interval
# *gc.gc_per_second
# *gc.gc_per_interval

[selfmon]
 #enable true/false enable/disable self monitoring
 enabled = true
 #send data Frequency
 freq = 60
 #prefix for measurement naming
 prefix = ""
 #inherit device tags
 inheritdevicetags = true
 #adds extra tags to the measurement config should be set as a csv - tag=value1,tag2=value2,...,tagN=valN
 extratags = [ "instance=pseriescollector01" ]


############################
# Embedded WebServer Config
############################

[http]
 #port where webserver will listen waiting for connections
 port   = 8090
 #Admin credentials to access to the pseriescollector agent
 adminuser = "adm1"
 adminpassword = "adm1pass"
 #When more than one instance you will need customize the cookie_id allowing navigate to all instances
 cookieid ="my_instance_cookie"
