#!/bin/sh

set -e

[ -f /etc/sysconfig/pseriescollector ] && . /etc/sysconfig/pseriescollector

startpseriescollector() {
  if [ -x /bin/systemctl ] ; then
		/bin/systemctl start pseriescollector.service
	elif [ -x /etc/init.d/pseriescollector ] ; then
		/etc/init.d/pseriescollector start
	elif [ -x /etc/rc.d/init.d/pseriescollector ] ; then
		/etc/rc.d/init.d/pseriescollector start
	fi
}

stoppseriescollector() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop pseriescollector.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/pseriescollector ] ; then
		/etc/init.d/pseriescollector stop
	elif [ -x /etc/rc.d/init.d/pseriescollector ] ; then
		/etc/rc.d/init.d/pseriescollector stop
	fi
}

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$RESIST_USER" ] && RESIST_USER="resist"
	[ -z "$RESIST_GROUP" ] && RESIST_GROUP="resist"
	if ! getent group "$RESIST_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$RESIST_GROUP"
	fi
	if ! getent passwd "$RESIST_USER" > /dev/null 2>&1 ; then
    useradd -r -g $RESIST_USER -d /usr/share/pseriescollector -s /sbin/nologin \
    -c "pseriescollector user" $RESIST_USER
	fi

 	# Set user permissions on /var/log/pseriescollector, /var/lib/pseriescollector
	mkdir -p /var/log/pseriescollector /var/lib/pseriescollector
	chown -R $RESIST_USER:$RESIST_GROUP /var/log/pseriescollector /var/lib/pseriescollector
	chmod 755 /var/log/pseriescollector /var/lib/pseriescollector

	# configuration files should not be modifiable by pseriescollector user, as this can be a security issue
	chown -Rh root:$RESIST_GROUP /etc/pseriescollector/*
	chmod 755 /etc/pseriescollector
	find /etc/pseriescollector -type f -exec chmod 640 {} ';'
	find /etc/pseriescollector -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure pseriescollector to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable pseriescollector.service"
    echo "### You can start pseriescollector by executing"
    echo " sudo /bin/systemctl start pseriescollector.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting pseriescollector by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add pseriescollector"
    echo "### In order to start pseriescollector, execute"
    echo " sudo service pseriescollector start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ -x /opt/pseriescollector/ ]; then
    echo "### Upgrading Notice ### "
    echo "-- New pseriescollector install home is /usr/share/pseriescollector"
    #echo "-- Please move sqlite3 database to /var/lib/pseriescollector/"
    echo "-- Notice: service name && binary changed to pseriescollector"
  fi

  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stoppseriescollector
    startpseriescollector
  fi
fi
